//! Test command for compiling CLIF files to .zkasm, running it, and verifying their results
//!
//! using [RunCommand](cranelift_reader::RunCommand)s.

use crate::runone::FileUpdate;
use crate::subtest::SubTest;
use anyhow::Context;
use cranelift_codegen::data_value::DataValue;
use cranelift_codegen::ir::Function;
use cranelift_codegen::isa::TargetIsa;
use cranelift_codegen::settings::Flags;
use cranelift_codegen::{self, ir};
use cranelift_interpreter::environment::FunctionStore;
use cranelift_reader::{parse_run_command, Details, TestCommand, TestFile};
use log::{info, trace};
use std::borrow::Cow;

use std::panic::{self, AssertUnwindSafe};

use cranelift_codegen::ir::function::FunctionParameters;
use cranelift_codegen::ir::ExternalName;
use cranelift_codegen::isa::zkasm;
use cranelift_codegen::{settings, FinalizedMachReloc, FinalizedRelocTarget};

struct TestRunZkasm;

pub fn subtest(parsed: &TestCommand) -> anyhow::Result<Box<dyn SubTest>> {
    assert_eq!(parsed.command, "run-zkasm");
    if !parsed.options.is_empty() {
        anyhow::bail!("No options allowed on {}", parsed);
    }
    Ok(Box::new(TestRunZkasm))
}

impl SubTest for TestRunZkasm {
    fn name(&self) -> &'static str {
        "run-zkasm"
    }

    fn is_mutating(&self) -> bool {
        false
    }

    fn needs_isa(&self) -> bool {
        false
    }

    /// Runs the entire subtest for a given target, invokes [Self::run] for running
    /// individual tests.
    fn run_target<'a>(
        &self,
        testfile: &TestFile,
        _: &mut FileUpdate,
        _: &'a str,
        _: &'a Flags,
        _: Option<&'a dyn TargetIsa>,
    ) -> anyhow::Result<()> {
        // We can build the FunctionStore once and reuse it
        let mut func_store = FunctionStore::default();
        for (func, _) in &testfile.functions {
            func_store.add(func.name.to_string(), &func);
        }

        for (func, details) in &testfile.functions {
            info!("Test: {}({}) runner-zkasm", self.name(), func.name);

            run_test(&func_store, func, details).context(self.name())?;
        }

        Ok(())
    }

    fn run(
        &self,
        _func: Cow<ir::Function>,
        _context: &crate::subtest::Context,
    ) -> anyhow::Result<()> {
        unreachable!()
    }
}

// TODO: replace by results of https://github.com/near/wasmtime/pull/213
struct ZkAsmExecutor {}

impl ZkAsmExecutor {
    pub fn new() -> ZkAsmExecutor {
        ZkAsmExecutor {}
    }

    pub fn execute(self, zkasm_function: &Vec<String>, args: &Vec<DataValue>) -> DataValue {
        for line in zkasm_function {
            println!("{}", line);
        }
        for arg in args {
            println!("{:#?}", arg);
        }
        todo!();
    }
}

fn run_test(func_store: &FunctionStore, func: &Function, details: &Details) -> anyhow::Result<()> {
    let zkasm_function = generate_zkasm(func_store, func);
    for comment in details.comments.iter() {
        if let Some(command) = parse_run_command(comment.text, &func.signature)? {
            trace!("Parsed run command: {}", command);
            let _ = command.run(|_func_name, run_args| {
                let mut args = Vec::with_capacity(run_args.len());
                args.extend_from_slice(run_args);
                let executor = ZkAsmExecutor::new();

                // just wrap to make CI green until executor is not ready
                // TODO: replace by actual execution and results checking
                let _ = panic::catch_unwind(AssertUnwindSafe(|| {
                    let _inner = executor.execute(&zkasm_function, &args);
                }));
                // let result = executor.execute(&zkasm_function, &args);
                // Ok(vec![result])
                Ok(Default::default())
            });
            // just to make CI green until runner is not ready
            // TODO: remove this
            // .map_err(|e| anyhow::anyhow!("{}", e))?;
        }
    }
    Ok(())
}

fn generate_zkasm(_func_store: &FunctionStore, func: &Function) -> Vec<String> {
    let flag_builder = settings::builder();
    let isa_builder = zkasm::isa_builder("zkasm-unknown-unknown".parse().unwrap());
    let isa = isa_builder
        .finish(settings::Flags::new(flag_builder))
        .unwrap();
    let mut comp_ctx = cranelift_codegen::Context::for_function(func.clone());
    let compiled_code = comp_ctx
        .compile(isa.as_ref(), &mut Default::default())
        .unwrap();
    let mut code_buffer = compiled_code.code_buffer().to_vec();
    fix_relocs(
        &mut code_buffer,
        &func.params,
        compiled_code.buffer.relocs(),
    );
    let code = std::str::from_utf8(&code_buffer).unwrap();
    let lines: Vec<String> = code.lines().map(|s| s.to_string()).collect();
    lines
}

// TODO: Relocations should be generated by a linker and/or clift itself.
fn fix_relocs(
    code_buffer: &mut Vec<u8>,
    params: &FunctionParameters,
    relocs: &[FinalizedMachReloc],
) {
    let mut delta = 0i32;
    for reloc in relocs {
        let start = (reloc.offset as i32 + delta) as usize;
        let mut pos = start;
        while code_buffer[pos] != b'\n' {
            pos += 1;
            delta -= 1;
        }

        let code =
            if let FinalizedRelocTarget::ExternalName(ExternalName::User(name)) = reloc.target {
                let name = &params.user_named_funcs()[name];
                if name.index == 0 {
                    b"  B :ASSERT".to_vec()
                } else {
                    format!("  zkPC + 2 => RR\n  :JMP(function_{})", name.index)
                        .as_bytes()
                        .to_vec()
                }
            } else {
                b"  UNKNOWN".to_vec()
            };
        delta += code.len() as i32;

        code_buffer.splice(start..pos, code);
    }
}
